### ISSUE TITLE
clone repo from virtual machine fails

### ISSUE THREAD

**Issue by tdcwilliams** [bopen/c3s-eqc-automatic-quality-control#17]
Hi Mattia,
I am logged into the virtual machine and have then become wp4 user with `su - wp4`

```
git clone git@github.com:bopen/c3s-eqc-automatic-quality-control.git
```
gives the error
```
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by malmans2** [comment]
Hi there,

The issue is that your ssh GH key is not on the VM.
You can just clone form http:
```
git clone https://github.com/bopen/c3s-eqc-automatic-quality-control.git
```

A couple of comments:
1. Do you need to install it on the VM? If you are downloading to install, `c3s-eqc-automatic-quality-control` is already installed in the wp4 conda env.
2. This repository might eventually disappear. The automatic-quality-control in not needed anymore as the original plan has changed. All templates and notebooks are available here: https://github.com/bopen/c3s-eqc-toolbox-template. So it's better if you open issues there in the future.

**Comment by tdcwilliams** [comment]
Hi @malmans2 - thanks, I'll try just using it from the wp4 conda env
